options:
  name-prefix:
    default: "cloudsupport-test"
    type: string
    description: |
        Name prefix to use for test instances
  cidr:
    default: "192.168.99.0/24"
    type: string
    description: |
        CIDR of test network to create. Note that changing the cidr will cause the network
        to be deleted and recreated. It is the operators responsibility to clean up any ports
        that may linger on the test network prior.
  image:
    default: "cloudsupport-image"
    type: string
    description: |
        Image for test instances
  vcpus:
    default: 24
    type: int
    description: |
        Default number of vcpus, note this can be overridden per-instance
  ram:
    default: 4096
    type: int
    description: |
        Ram for instances
  disk:
    default: 4
    type: int
    description: |
        Disk for instances in GB
  ssl_ca:
    default: ""
    type: string
    description: |
        TLS CA certficate, to be added as OS_CACERT
  clouds-yaml:
    default: ""
    type: string
    description: |
        clouds.yaml with authentication info
  ssh-key:
    default: ''
    type: string
    description: |
      juju ssh key for connectivity tests
  stale_server_check:
    default: False
    type: boolean
    description: |
      Either enable or disable the stale server check. If it is enabled
      the stale_project_uuids option is mandatory to be set.
  stale_warn_days:
    type: int
    default: 7
    description: Days to change check to warning state.
  stale_crit_days:
    type: int
    default: 14
    description: Server overdue days to change check to critical state.
  stale_name_prefix:
    type: string
    default: ""
    description: |
      Name prefix to match servers, if not specified the name-prefix from
      the charm config is taken. This acts as an override specifically for the
      stale server check.
  stale_project_uuids:
    type: string
    default: ""
    description: |
      A comma separated list of project UUIDs to check for stale servers.
  stale_ignored_uuids:
    type: string
    default: ""
    description: |
      A comma separated list of server UUIDs to be ignored/excluded from the stale server check.

